#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

LOG="`tempfile`"
function finish {
    LOG2="`tempfile`"
    head -n 1 $LOG >> $LOG2
    echo >> $LOG2
    tail -n +2 $LOG >> $LOG2
    cat $LOG2
    rm $LOG $LOG2
}
trap finish EXIT

if [ "$1" != "" ] && [ "$1" != "engine" ] && [ "$1" != "webui" ]; then
    echo "'$1' is not a part of Pipeline 2. Must be either 'engine' or 'webui'" >> $LOG 2>&1
else
    ./reinstall.engine >> $LOG 2>&1
    ./reinstall.webui >> $LOG 2>&1
fi

exit 0

